package scenario_import

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/gberns/kerf/internal/sim/scenario"
)

// MarshalScenario renders a scenario as YAML with a leading provenance
// comment block. The output is byte-for-byte deterministic for a given
// input.
func MarshalScenario(sc *scenario.Scenario, sourceDesc string, notes []string) ([]byte, error) {
	if sc == nil {
		return nil, fmt.Errorf("scenario_import: nil scenario")
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "# Generated by `kerfsim import` from %s.\n", sourceDesc)
	fmt.Fprintln(&buf, "#")
	fmt.Fprintln(&buf, "# NOTE: agent_model.duration and bead_arrivals.generator carry")
	fmt.Fprintln(&buf, "# defaults only. They should be tuned per Plan 012 B-step3 fitted")
	fmt.Fprintln(&buf, "# distributions before drawing scoring conclusions.")
	for _, n := range notes {
		fmt.Fprintf(&buf, "# %s\n", n)
	}
	fmt.Fprintln(&buf)

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(sc); err != nil {
		return nil, fmt.Errorf("scenario_import: encode: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("scenario_import: encode close: %w", err)
	}
	return buf.Bytes(), nil
}
